---
--- Generated by Luanalysis
--- Created by 23979.
--- DateTime: 2024/7/22 10:22
---
-- 1.参数列表
-- 1.1 优惠券Id
local voucherId = ARGV[1]
-- 1.2 用户id
local userId = ARGV[2]

-- 2.数据key
-- 2.1 库存key
local stockKey = 'seckill:stock:' .. voucherId
-- 2.2 订单key
local orderKey = 'seckill:order:' .. voucherId

-- 3.脚本业务
-- 3.1 判断库存是否充足 get stockKey
local stock = redis.call('get', stockKey)

-- 检查库存是否为 nil 或者将库存转换为数字
if (not stock) or (tonumber(stock) <= 0) then
    -- 3.1.2 库存不足,返回1
    return 1
end

-- 3.2 判断用户是否已经下过单
if (redis.call('sismember', orderKey, userId) == 1) then
    -- 3.2.2 存在，说明重复下单，返回2
    return 2
end

-- 3.3 扣库存 incrby stockKey -1
redis.call('incrby', stockKey, -1)

-- 3.4 下单(保存用户) sadd orderKey userId
redis.call('sadd', orderKey, userId)

-- 3.5 用户有下单资格，返回0
return 0

